function batch_preverify_mj2_files_after_mj2_from_tif(mj2_folder_name, tif_folder_name, do_submit)
    % Makes sure all the big target files are present in the the destination, and
    % are similar to their source files.
    
    bsub_options = '-n4 -P mouselight -W 59 -J verify-frozen' ;
    find_and_batch(tif_folder_name, ...
                   @does_match_raw_tile_tif_name, ...
                   @preverify_single_file_after_mj2_from_tif, ...
                   do_submit, ...
                   bsub_options, ...
                   tif_folder_name, ...
                   mj2_folder_name) ;
end
