function batch_preverify_tif_files_after_mj2_from_tif(mj2_folder_name, tif_folder_name, do_submit, maximum_running_slot_count)
    % Makes sure all the big target files are present in the the destination, and
    % are similar to their source files.
    
    slots_per_job = 4 ;
    bsub_options = '-P mouselight -W 59 -J verify-frozen' ;
    find_and_batch(tif_folder_name, ...
                   @does_need_preverification_after_freezing, ...
                   @preverify_single_tif_file_after_mj2_from_tif, ...
                   do_submit, ...
                   maximum_running_slot_count, ...
                   slots_per_job, ...
                   bsub_options, ...
                   tif_folder_name, ...
                   mj2_folder_name) ;
end
