function check_certs_after_verifying_thawing(input_root_folder_path, output_root_folder_path)
    % Makes sure there's a .similar-tif-exists for each .mj2 file in
    % input_root_folder_path.
    find_and_verify(...
        input_root_folder_path, ...
        @is_a_mj2_in_a_folder_with_no_subfolders, ...
        @check_single_cert_after_verifying_thawing, ...
        input_root_folder_path, ...
        output_root_folder_path) ;
end
