function result = find_and_count(base_folder_path, is_file_a_keeper_predicate, varargin)
    result = ...
        find_and_list_helper(base_folder_path, ...
                             is_file_a_keeper_predicate, ...
                             0, ...
                             varargin{:}) ;
end



function result = ...
        find_and_list_helper(base_folder_path, ...
                             is_file_a_keeper_predicate, ...
                             incoming_count, ...
                             varargin)
    count_so_far = incoming_count ;
    [file_names, is_file_a_folder] = simple_dir(base_folder_path) ;
    file_count = length(file_names) ;
    for i = 1 : file_count ,
        file_name = file_names{i} ;
        is_this_file_a_folder = is_file_a_folder(i) ;
        file_path = fullfile(base_folder_path, file_name) ;
        if is_this_file_a_folder ,
            % if a folder, recurse
            count_so_far = ...
                find_and_list_helper(file_path, ...
                                     is_file_a_keeper_predicate, ...
                                     count_so_far, ...
                                     varargin{:}) ;
        else
            if feval(is_file_a_keeper_predicate, file_path, varargin{:}) ,
                count_so_far = count_so_far + 1 ;
            end
        end
    end    
    result = count_so_far ;
end
