function verify_non_tif_files_after_thawing(output_root_folder_path, input_root_folder_path)
    % Makes sure all the output files are present in the the destination, and have
    % the same size and md5sum.
    
    find_and_verify(input_root_folder_path, ...
                    @does_file_name_not_end_in_dot_mj2, ...
                    @verify_single_non_stack_file, ...
                    input_root_folder_path, ...
                    output_root_folder_path) ;
end
