function is_all_well = verify_small_files_after_mj2_from_tif(mj2_root_folder_path, tif_root_folder_path)
    % Makes sure all the target files are present in the the destination, and have
    % the right size, or at least a plausible size in the case of .mj2's.
    
    is_all_well = ...
        find_and_verify(tif_root_folder_path, ...
                        @does_file_name_not_end_in_dot_tif, ...
                        @verify_single_small_file_after_mj2_from_tif, ...
                        tif_root_folder_path, ...
                        mj2_root_folder_path) ;
end
