function verify_tif_files_after_mj2_from_tif(tif_root_folder_path, mj2_root_folder_path)
    % Makes sure there's a .similar-mj2-exists for each .tif file in
    % tif_root_folder_path.    
    find_and_verify(tif_root_folder_path, ...
                    @does_file_name_end_in_dot_tif, ...
                    @verify_single_tif_file_after_mj2_from_tif, ...
                    tif_root_folder_path, ...
                    mj2_root_folder_path) ;
end
   